// ADD A NEW SUBJECT
POST http://localhost:5000/private/class-stream/add-class-stream
Content-Type: application/json

{
    "name": "Class : 6"
}

###

// GET ALL SUBJECTS
GET http://localhost:5000/private/class-stream/get-class-stream
Content-Type: application/json


###